import fs from 'node:fs'

const writeMode=process.argv.includes('--write')
const read=(path)=>JSON.parse(fs.readFileSync(path,'utf8'))
const normalize=(value)=>value.toLocaleLowerCase('en-US').replace(/[^a-z0-9]+/g,' ').trim()
const normalizeZh=(value)=>value.trim().replace(/\s+/g,'')
const tokens=(value)=>value.toLocaleLowerCase('en-US').trim().split(/\s+/u).map((token)=>token.replace(/^[^a-z0-9]+|[^a-z0-9]+$/gu,'')).filter(Boolean)
function fingerprint(value){let hash=0x811c9dc5;for(const character of value){hash^=character.charCodeAt(0);hash=Math.imul(hash,0x01000193)}return(hash>>>0).toString(16).padStart(8,'0')}
const key=(row)=>`${normalize(row.term)}|${normalizeZh(row.meaningZh)}`

const phrases=[
  ['missed-connection protection','错过衔接行程保障'],['through-checked baggage','直挂行李'],['minimum connection time','最低转机时间'],['involuntary rebooking','非自愿改签'],['fare-rule restriction','票价规则限制'],
  ['accessible transfer route','无障碍转乘路线'],['medical preauthorization','医疗预授权'],['emergency repatriation','紧急遣返'],['trip-interruption coverage','行程中断保障'],['delayed-baggage reimbursement','行李延误报销'],
  ['cross-border rental','跨境租车'],['roadside recovery','道路救援拖离'],['security-deposit release','押金解除'],['duplicate-charge dispute','重复扣款争议'],['dynamic currency conversion','动态货币转换'],
  ['overnight disruption','过夜行程中断'],['replacement transport','替代交通'],['step-free boarding','无台阶登乘'],['dietary cross-contact','饮食交叉接触'],['prescription replacement','处方药补配'],
]

const groups=[
  ['Can you confirm {x} appears in the new booking?','您能确认新预订是否包含{x}吗？',[['my checked-bag allowance','我的托运行李额度'],['the airport transfer','机场接送'],['breakfast for both guests','两位客人的早餐'],['wheelchair assistance','轮椅协助'],['the flexible return date','灵活返程日期']]],
  ['The revised itinerary leaves only {x} for the connection.','修改后的行程只留出{x}用于转机。',[['thirty minutes','三十分钟'],['one short platform change','一次很短的站台换乘'],['a single security lane','一条安检通道'],['no time for immigration','没有入境检查时间'],['ten minutes between terminals','航站楼之间十分钟']]],
  ['My confirmation shows {x}, but the provider says otherwise.','我的确认单显示{x}，但服务方说法不同。',[['a refundable rate','可退款价格'],['two included bags','包含两件行李'],['free cancellation today','今天可免费取消'],['an accessible room','无障碍房间'],['a prepaid reservation','已预付的预订']]],
  ['If {x}, what can you arrange?','如果{x}，您今天能安排什么替代方案？',[['the last train is canceled','末班火车取消'],['my room remains unavailable','我的房间仍无法提供'],['the lift stays closed','电梯继续关闭'],['the medicine is out of stock','药物缺货'],['the rental car breaks down','租赁车辆抛锚']]],
  ['Can you keep {x} while changing everything else?','更改其余行程时，您能保留{x}吗？',[['our original seats','我们原来的座位'],['the first flight','第一程航班'],['the prepaid hotel night','已预付的酒店住宿'],['the existing insurance cover','现有保险保障'],['our return reservation','我们的返程预订']]],
  ['Please explain why {x} disappeared after the schedule change.','请说明时刻变更后为什么取消了{x}。',[['my seat assignment','我的座位安排'],['the baggage transfer','行李转运'],['our meal request','我们的餐食要求'],['the accessible boarding service','无障碍登乘服务'],['the hotel voucher','酒店凭证']]],
  ['Would {x} still apply after I accept this replacement?','我接受这个替代方案后，{x}仍然适用吗？',[['the original cancellation terms','原取消条款'],['my travel insurance','我的旅行保险'],['the same baggage allowance','相同的行李额度'],['our seat reservations','我们的座位预订'],['the quoted room rate','所报房价']]],
  ['I need proof that {x} before I leave.','我离开前需要书面确认{x}。',[['the refund was approved','退款已批准'],['the bag will be delivered','行李会被送达'],['the booking was corrected','预订已更正'],['the deposit was released','押金已解除'],['the assistance was requested','协助已申请']]],
  ['Could you compare {x} with the new option?','您能把{x}与刚提供的方案比较一下吗？',[['the total travel time','总行程时间'],['the fare restrictions','票价限制'],['the overnight arrangements','过夜安排'],['the insurance coverage','保险保障'],['the accessible route','无障碍路线']]],
  ['Because {x}, I need help tonight.','由于{x}，我今晚需要帮助。',[['my medicine is in the delayed bag','我的药在延误行李中'],['the replacement hotel has stairs','替代酒店有楼梯'],['the final train has departed','末班火车已经开走'],['my passport was stolen','我的护照被盗'],['the rental office is closed','租车门店已关闭']]],
  ['If {x}, who can help?','服务台关闭后，如果{x}，我应该去哪里？',[['my flight is canceled','我的航班取消'],['the luggage still has not arrived','行李仍未到达'],['my room key stops working','我的房卡失效'],['the symptoms become worse','症状加重'],['the car will not start','车辆无法启动']]],
  ['How will {x} affect the rest of my journey?','{x}会怎样影响我之后的行程？',[['this airport change','这次机场变更'],['the delayed passport replacement','护照补办延误'],['the missed rail connection','错过铁路衔接'],['the shortened visa validity','签证有效期缩短'],['the road closure tomorrow','明天的道路封闭']]],
  ['Could you send {x} directly to my next hotel?','服务方能把{x}直接送到我下一家酒店吗？',[['the delayed suitcase','延误的行李箱'],['the replacement medicine','补配的药物'],['the corrected rail pass','更正后的铁路通票'],['the revised rental agreement','修改后的租车合同'],['the missing travel documents','缺失的旅行文件']]],
  ['Before charging my card, please confirm {x}.','刷卡前，请确认{x}。',[['the final amount in local currency','以当地货币计算的最终金额'],['which deposit is refundable','哪一笔押金可退'],['the additional driver fee','额外驾驶人费用'],['the revised room total','修改后的房费总额'],['the fare difference and taxes','票价差额和税费']]],
  ['The receipt includes {x} that I did not authorize.','收据包含我未授权的{x}。',[['a second security deposit','第二笔押金'],['an optional insurance upgrade','可选保险升级'],['a minibar purchase','迷你吧消费'],['a currency-conversion fee','货币转换费'],['an extra rental day','额外一天租期']]],
  ['Can you separate {x} from the rest?','您能把{x}与账单中无争议的部分分开吗？',[['the duplicate room charge','重复房费'],['the incorrect fuel fee','错误燃油费'],['the canceled excursion','已取消的游览项目'],['the unrequested meal','未点的餐食'],['the disputed exchange markup','有争议的汇率加价']]],
  ['What proof do you need to process {x}?','处理{x}需要什么证明？',[['the delayed-baggage claim','行李延误理赔'],['the medical reimbursement','医疗报销'],['the canceled-flight refund','航班取消退款'],['the damaged-car report','车辆损伤报告'],['the stolen-passport replacement','被盗护照补办']]],
  ['My insurer needs {x} from the treating clinic.','我的保险公司需要诊所提供{x}。',[['an itemized invoice','明细账单'],['the diagnosis in English','英文诊断'],['the prescribed dosage','处方剂量'],['the treatment date','治疗日期'],['the doctor’s signature','医生签名']]],
  ['Is {x} safe to use during a long flight?','在长途飞行期间使用{x}安全吗？',[['this new medication','这种新药'],['the prescribed compression stocking','处方压力袜'],['the portable oxygen device','便携氧气设备'],['the replacement inhaler','补配的吸入器'],['this motion-sickness patch','这片晕车贴']]],
  ['Please check whether {x} contains my listed allergen.','请确认{x}是否含有我列出的过敏原。',[['the replacement meal','替代餐食'],['the cooking oil','食用油'],['the prepared sauce','调制酱汁'],['the dessert topping','甜点配料'],['the packaged snack','包装零食']]],
  ['The accessible route is blocked by {x}.','无障碍路线被{x}阻挡。',[['a locked service door','上锁的服务门'],['a broken platform lift','损坏的站台电梯'],['construction near the entrance','入口附近施工'],['stairs at the transfer point','换乘点的楼梯'],['an out-of-service escalator','停用的自动扶梯']]],
  ['Could you arrange {x} without separating our group?','您能安排{x}而不把我们同行人员分开吗？',[['a later connecting flight','较晚的衔接航班'],['accessible seats together','相邻的无障碍座位'],['rooms on the same floor','同楼层的房间'],['the replacement rail journey','替代铁路行程'],['transport to another airport','前往另一机场的交通']]],
  ['The rental agreement does not show {x} we requested.','租车合同没有显示我们申请的{x}。',[['the second driver','第二位驾驶人'],['cross-border permission','跨境许可'],['the child seat','儿童座椅'],['full roadside assistance','完整道路救援'],['the agreed return location','约定还车地点']]],
  ['If the car fails, can you provide {x}?','如果车辆无法修复，你们会提供{x}吗？',[['a comparable replacement car','同等替代车辆'],['transport back to the city','返回城市的交通'],['overnight accommodation nearby','附近过夜住宿'],['a refund for unused days','未使用天数退款'],['help moving our luggage','转运行李的帮助']]],
  ['Which route avoids {x} without adding another transfer?','哪条路线能避开{x}且不增加换乘？',[['the closed mountain road','封闭的山路'],['stairs at Central Station','中央车站的楼梯'],['the strike-affected line','受罢工影响的线路'],['the flooded underpass','积水的地下通道'],['the security closure downtown','市中心的安全封锁']]],
  ['The replacement service arrives after {x} closes.','替代服务到达时，{x}已经关闭。',[['the hotel reception','酒店前台'],['the rental counter','租车柜台'],['the border checkpoint','边境检查站'],['the final ferry gate','末班渡轮登船口'],['the baggage office','行李办公室']]],
  ['Could you change only {x} and keep everything else?','您能只更改{x}，其他保持不变吗？',[['the return flight','返程航班'],['the second train','第二趟列车'],['the final hotel night','最后一晚酒店'],['the airport transfer','机场接送'],['the rental pickup time','取车时间']]],
  ['The ticket shows {x}, not the confirmed choice.','修改后的票显示{x}，而不是已确认的选择。',[['a different arrival airport','另一个到达机场'],['a longer overnight connection','更长的过夜转机'],['a seat without extra space','没有额外空间的座位'],['a nonrefundable fare','不可退款票价'],['a route with three changes','需要三次换乘的路线']]],
  ['Who can help if {x} outside business hours?','非营业时间发生{x}时，我应该联系谁？',[['the passport is found','护照被找回'],['the delayed bag arrives','延误行李到达'],['the rental car fails','租赁车辆故障'],['the medical condition changes','病情变化'],['the security alert is updated','安全警报更新']]],
  ['Can you update {x} without canceling the existing reservation?','您能更新{x}而不取消现有预订吗？',[['my passport number','我的护照号码'],['the delivery address','送达地址'],['the emergency contact','紧急联系人'],['the accessibility request','无障碍协助申请'],['the return date','返程日期']]],
  ['The agent said {x}. The confirmation differs.','有人告诉我{x}，但书面确认内容不同。',[['the change would be free','变更免费'],['the bag was checked through','行李已直挂'],['breakfast was included','包含早餐'],['the deposit was refundable','押金可退'],['the medicine was covered','药费在保障范围内']]],
  ['Where does {x} appear in the confirmation?','您能指出确认单中哪里写了{x}吗？',[['the cancellation deadline','取消截止时间'],['the baggage restriction','行李限制'],['the additional service fee','额外服务费'],['the excluded treatment','不承保的治疗'],['the alternate pickup point','替代接车点']]],
  ['What happens to {x} when the reservation is divided?','预订拆分后，{x}会怎样处理？',[['our checked luggage','我们的托运行李'],['the shared hotel deposit','共同的酒店押金'],['the family seat request','家庭座位申请'],['the travel-insurance record','旅行保险记录'],['the return transfer','返程接送']]],
  ['Keep {x} active until the replacement is confirmed.','替代方案完全确认前，请保持{x}有效。',[['the original ticket','原机票'],['our current room','我们当前的房间'],['the first rental booking','第一份租车预订'],['the existing rail passes','现有铁路通票'],['the scheduled airport pickup','已安排的机场接送']]],
  ['Does {x} meet the entry rules for my destination?','{x}符合我目的地的入境规定吗？',[['this emergency passport','这本紧急护照'],['the temporary visa letter','临时签证函'],['my digital vaccination record','我的电子疫苗记录'],['the revised return ticket','修改后的返程票'],['this insurance certificate','这份保险证明']]],
  ['The proposed solution creates {x} later in the trip.','这个建议方案会在后续行程中造成{x}。',[['another missed connection','再次错过衔接'],['an uncovered hotel night','一晚无保障住宿'],['a visa-validity problem','签证有效期问题'],['an inaccessible transfer','一次无法无障碍完成的换乘'],['a second baggage recheck','再次重新托运行李']]],
]

function released(){const index=read('content/curriculum/package-index.v1.json');return index.lessonFiles.flatMap((file)=>read(file).lessons).flatMap((lesson)=>lesson.learningUnits.filter((unit)=>unit.domain==='vocabulary').flatMap((unit)=>unit.activity.items.map((item)=>({...item,difficulty:item.growthDifficultyLevel??unit.difficultyLevel}))))}
function author(){
  const earlier=[...read('content/curriculum/daily-level-content-batch-a.v2.json').records,...read('content/curriculum/daily-level-content-batch-b.v2.json').records]
  const rows=[...phrases.map(([term,meaningZh])=>({term,meaningZh,surfaceType:'short-phrase'})),...groups.flatMap(([template,templateZh,topics])=>topics.map(([x,xZh])=>({term:template.replace('{x}',x),meaningZh:templateZh.replace('{x}',xZh),surfaceType:'functional-utterance'})))]
  if(rows.length!==200)throw new Error(`C1 expected 200 authored rows, got ${rows.length}.`)
  if(new Set(rows.map((row)=>normalize(row.term))).size!==200)throw new Error('C1 English forms are duplicated.')
  if(new Set([...earlier,...rows].map((row)=>normalize(row.term))).size!==2200)throw new Error('C1 overlaps Batch A or B.')
  if(rows.some((row)=>tokens(row.term).length>12))throw new Error(`C1 over-token item: ${rows.find((row)=>tokens(row.term).length>12).term}`)
  const records=rows.map((row,index)=>{const form=normalize(row.term);return{sourceItemId:`qa-r17-003-c1:${String(index+1).padStart(3,'0')}`,dailyKnowledgeId:`daily-knowledge-v2:phrase:${fingerprint(`${form}|${normalizeZh(row.meaningZh)}`)}`,levelId:'senior-1',labelZh:'高一',growthDifficultyLevel:5,term:row.term,meaningZh:row.meaningZh,partOfSpeech:row.surfaceType,exampleEn:row.term,exampleZh:row.meaningZh,authoring:{lexicalFrequencyBand:'functional',abstractionBand:'multi-step-function',surfaceType:row.surfaceType,grammarFeatures:row.surfaceType==='functional-utterance'?['multi-step-spoken-turn']:[],travelUse:'complex-travel-resolution',contentReviewStatus:'candidate-reviewed'}}})
  const old=released().filter((row)=>row.difficulty===5),byContent=new Map(records.map((row)=>[key(row),row]))
  const entries=old.map((source)=>{const target=byContent.get(key(source));return target?{sourceDailyKnowledgeId:source.dailyKnowledgeId??`legacy-daily-source-v1:${source.id}`,sourceIdentityKind:source.dailyKnowledgeId?'stable-daily-knowledge-v1':'legacy-source-item-fallback',sourceItemId:source.id,disposition:'equivalent',targetDailyKnowledgeId:target.dailyKnowledgeId,evidenceTransferAllowed:true}:{sourceDailyKnowledgeId:source.dailyKnowledgeId??`legacy-daily-source-v1:${source.id}`,sourceIdentityKind:source.dailyKnowledgeId?'stable-daily-knowledge-v1':'legacy-source-item-fallback',sourceItemId:source.id,disposition:'retired',evidenceTransferAllowed:false}})
  const mapped=new Set(entries.flatMap((entry)=>entry.targetDailyKnowledgeId?[entry.targetDailyKnowledgeId]:[]))
  return{content:{schemaVersion:1,documentType:'daily-level-content-batch',contentVersion:'2.0.0-c1',identityVersion:'daily-knowledge-v2',releaseStatus:'candidate-not-deployable-until-c2-c5',levels:[{id:'senior-1',labelZh:'高一',recordCount:200}],records},migration:{schemaVersion:1,documentType:'daily-level-identity-migration',migrationVersion:'daily-level-v1-to-v2-c1',releaseStatus:'candidate',sourceIdentityVersion:'daily-knowledge-v1',targetIdentityVersion:'daily-knowledge-v2',sourceRecordCount:old.length,canonicalTargetCount:200,entries,newIdentities:records.filter((row)=>!mapped.has(row.dailyKnowledgeId)).map((row)=>row.dailyKnowledgeId)}}
}
const{content,migration}=author();for(const[path,value]of[['content/curriculum/daily-level-content-c1.v2.json',content],['content/curriculum/daily-level-identity-migration-c1.v1.json',migration]]){const serialized=`${JSON.stringify(value,null,2)}\n`;if(writeMode)fs.writeFileSync(path,serialized);else if(fs.readFileSync(path,'utf8')!==serialized)throw new Error(`${path} is stale; run with --write.`)}
console.log(`C1 authored: ${content.records.length}; old sources ${migration.sourceRecordCount}; retired ${migration.entries.filter((row)=>row.disposition==='retired').length}.`)
